const BAND_SESSION_SECONDS = 60;
const BAND_BASE_INTERVAL_MS = 1000;
const BAND_MIN_INTERVAL_MS = 500;
const BAND_BASE_TRAVEL_MS = 2100;
const BAND_MIN_TRAVEL_MS = 1500;
const BAND_HEIGHT = 56;
const BAND_MARGIN_X = 12;
const BAND_ZONE_WIDTH = 100;

const BUTTON_SIZE = 40;
const BUTTON_RADIUS = BUTTON_SIZE / 2;
const BUTTON_GLOW_PADDING = 12;
const BUTTON_PRESS_SCALE = 0.88;
const BUTTON_MIN_DISTANCE = 50;
const BUTTON_LANE_EDGE_MARGIN = 16;
const BUTTON_CHARACTER_EXCLUSION_HALF_WIDTH = 90;
const BUTTON_VERTICAL_TOP_MARGIN = 100;
const BUTTON_VERTICAL_BOTTOM_MARGIN = 200;
const BUTTON_PLACEMENT_MAX_ATTEMPTS = 200;

const TAP_MONG_RATIO = 1.8;

// 판정 기준은 화면에 실제로 그려지는 중앙 박스(BAND_ZONE_WIDTH) 안에 단어(텍스트)가
// 얼마나 겹쳐 있는지(단어 너비 대비 비율)를 기준으로 한다.
// 예) perfect는 단어의 90% 이상이 중앙 박스 안에 있어야 한다.
const JUDGE_PERFECT_OVERLAP_RATIO = 0.9;
const JUDGE_GOOD_OVERLAP_RATIO = 0.4;
const JUDGE_NOT_GOOD_OVERLAP_RATIO = 0.1;

const FOOTER_HEIGHT = 56;

// Phaser draws these regions onto its internal <canvas>, so they have no DOM
// node for the tutorial (driver.js) to target. PlayScreen renders invisible
// overlay divs positioned with this same geometry so driver.js has something
// to highlight.
const TUTORIAL_BAND_TARGET_LAYOUT = { top: 45, height: 60 };
const TUTORIAL_BUTTON_TARGET_LAYOUT = {
  top: BAND_HEIGHT + BUTTON_RADIUS + BUTTON_VERTICAL_TOP_MARGIN - 20,
  bottomOffset: BUTTON_RADIUS + BUTTON_VERTICAL_BOTTOM_MARGIN - 25,
  sideMargin: BUTTON_LANE_EDGE_MARGIN + BUTTON_RADIUS - 20,
};

export {
  BAND_SESSION_SECONDS,
  BAND_BASE_INTERVAL_MS,
  BAND_MIN_INTERVAL_MS,
  BAND_BASE_TRAVEL_MS,
  BAND_MIN_TRAVEL_MS,
  BAND_HEIGHT,
  BAND_MARGIN_X,
  BAND_ZONE_WIDTH,
  BUTTON_RADIUS,
  BUTTON_GLOW_PADDING,
  BUTTON_PRESS_SCALE,
  BUTTON_MIN_DISTANCE,
  BUTTON_LANE_EDGE_MARGIN,
  BUTTON_CHARACTER_EXCLUSION_HALF_WIDTH,
  BUTTON_VERTICAL_TOP_MARGIN,
  BUTTON_VERTICAL_BOTTOM_MARGIN,
  BUTTON_PLACEMENT_MAX_ATTEMPTS,
  TAP_MONG_RATIO,
  JUDGE_PERFECT_OVERLAP_RATIO,
  JUDGE_GOOD_OVERLAP_RATIO,
  JUDGE_NOT_GOOD_OVERLAP_RATIO,
  FOOTER_HEIGHT,
  TUTORIAL_BAND_TARGET_LAYOUT,
  TUTORIAL_BUTTON_TARGET_LAYOUT,
};
