const BAND_SESSION_SECONDS = 60;
const BAND_BASE_INTERVAL_MS = 1000;
const BAND_MIN_INTERVAL_MS = 500;
const BAND_BASE_TRAVEL_MS = 1800;
const BAND_MIN_TRAVEL_MS = 1100;
const BAND_HEIGHT = 56;
const BAND_MARGIN_X = 12;
const BAND_ZONE_WIDTH = 100;

const BUTTON_SIZE = 45;
const BUTTON_RADIUS = BUTTON_SIZE / 2;
const BUTTON_GLOW_PADDING = 12;
const BUTTON_PRESS_SCALE = 0.88;
const BUTTON_MIN_DISTANCE = 50;
const BUTTON_LANE_EDGE_MARGIN = 16;
const BUTTON_CHARACTER_EXCLUSION_HALF_WIDTH = 90;
const BUTTON_VERTICAL_TOP_MARGIN = 100;
const BUTTON_VERTICAL_BOTTOM_MARGIN = 200;
const BUTTON_PLACEMENT_MAX_ATTEMPTS = 200;

const TAP_MONG_RATIO = 1.8;

const JUDGE_PERFECT_MS = 120;
const JUDGE_GOOD_MS = 280;

const FOOTER_HEIGHT = 56;

// Phaser draws these regions onto its internal <canvas>, so they have no DOM
// node for the tutorial (driver.js) to target. PlayScreen renders invisible
// overlay divs positioned with this same geometry so driver.js has something
// to highlight.
const TUTORIAL_BAND_TARGET_LAYOUT = { top: 45, height: 60 };
const TUTORIAL_BUTTON_TARGET_LAYOUT = {
  top: BAND_HEIGHT + BUTTON_RADIUS + BUTTON_VERTICAL_TOP_MARGIN - 20,
  bottomOffset: BUTTON_RADIUS + BUTTON_VERTICAL_BOTTOM_MARGIN - 25,
  sideMargin: BUTTON_LANE_EDGE_MARGIN + BUTTON_RADIUS - 20,
};

export {
  BAND_SESSION_SECONDS,
  BAND_BASE_INTERVAL_MS,
  BAND_MIN_INTERVAL_MS,
  BAND_BASE_TRAVEL_MS,
  BAND_MIN_TRAVEL_MS,
  BAND_HEIGHT,
  BAND_MARGIN_X,
  BAND_ZONE_WIDTH,
  BUTTON_RADIUS,
  BUTTON_GLOW_PADDING,
  BUTTON_PRESS_SCALE,
  BUTTON_MIN_DISTANCE,
  BUTTON_LANE_EDGE_MARGIN,
  BUTTON_CHARACTER_EXCLUSION_HALF_WIDTH,
  BUTTON_VERTICAL_TOP_MARGIN,
  BUTTON_VERTICAL_BOTTOM_MARGIN,
  BUTTON_PLACEMENT_MAX_ATTEMPTS,
  TAP_MONG_RATIO,
  JUDGE_PERFECT_MS,
  JUDGE_GOOD_MS,
  FOOTER_HEIGHT,
  TUTORIAL_BAND_TARGET_LAYOUT,
  TUTORIAL_BUTTON_TARGET_LAYOUT,
};
